sudo: required
services:
  - docker

before_install:
  - docker build -t jaromirrivera/react-test -f Dockerfile.dev ./client

script:
  - docker run jaromirrivera/react-test npm run test -- --coverage

after_success:
  - docker build -t jaromirrivera/multi-client ./client
  - docker build -t jaromirrivera/multi-nginx ./nginx
  - docker build -t jaromirrivera/multi-server ./server
  - docker build -t jaromirrivera/multi-worker ./worker


